#!/bin/sh

# Console user
consoleUser=$(stat -f %Su /dev/console)

# F5 Search and Destroy
dirlist=`mdfind -name "BIG-IP Edge Client"`

###########
# LOGFILE #
###########
# Create hidden directory for log file
mkdir /Users/$consoleUser/.ntech
datestamp=$(date +%Y%m%d)
logfile=/Users/$consoleUser/.ntech/vpnutil-$datestamp.log

#############
# FUNCTIONS #
#############
beginInstall() {
    echo "Starting install: $1 at $(date +%H:%M:%S)" | tee -a $logfile
}

installComplete() {
    echo "Install complete: $1 at $(date +%H:%M:%S)\n" | tee -a $logfile
}

echo "Starting machine configuration: $(date +%H:%M:%S)\n" | tee -a $logfile

###############
# CHOICE  #####
###############

# Get the logged in UID
loggedInUID=$(id -u $consoleUser)

choice=$(/bin/launchctl asuser "${loggedInUID}" sudo -iu "${consoleUser}" /usr/bin/osascript<<EOF
    tell application "System Events"
    activate
    set myAnswer to button returned of (display dialog "What would you like me to do" buttons {"Remove F5 Only", "Remove F5 And Install Pulse"})
    end tell
    return myAnswer
EOF)

if $choice="Remove F5 Only";
then
   
# Check if F5 is running and kill

pid=$(ps -fe | grep '[B]IG-IP Edge Client' | awk '{print $2}')
if [[ -n $pid ]]; then
    echo "F5 is running...killing process" | tee -a $logfile
    kill $pid
else
    echo "F5 is not running" | tee -a $logfile
fi

# Remove F5 App
echo "Removig F5 app if exists in App folder at $(date +%H:%M:%S)" | tee -a $logfile
F5APP=/Applications/BIG-IP\ Edge\ Client.app
if [[ -d "$F5APP" ]]
then
    echo "Big IP app exists. Removing at $(date +%H:%M:%S)" | tee -a $logfile
    /bin/rm -rf /Applications/BIG-IP\ Edge\ Client.app
else
echo "Big IP app does not exist" | tee -a $logfile
fi

#Cleaning up F5 files:
echo "Removig F5 plugin if exists in plugin folder at $(date +%H:%M:%S)" | tee -a $logfile
F5PLUGIN=/Library/Internet\ Plug-Ins/F5\ SSL\ VPN\ Plugin.plugin/
if [[ -d "$F5PLUGIN" ]]
then
    echo "Big IP plugin exists. Removing at $(date +%H:%M:%S)" | tee -a $logfile
    /bin/rm -rf /Library/Internet\ Plug-Ins/F5\ SSL\ VPN\ Plugin.plugin/
else
    echo "Big IP plugin does not exist" | tee -a $logfile
fi

echo "Removig F5 Library if exists in Library folder at $(date +%H:%M:%S)" | tee -a $logfile
F5LIB=/Users/$consoleUser/Library/F5Networks/
if [[ -d "$F5LIB" ]]
then
    echo "F5Network Library exists. Removing at $(date +%H:%M:%S)" | tee -a $logfile
    /bin/rm -rf /Users/$consoleUser/Library/F5Networks/
else 
    echo "F5Network Library does not exist" | tee -a $logfile
fi

echo "Removig F5 Cache if exists at $(date +%H:%M:%S)" | tee -a $logfile
F5CACHE=/Users/$consoleUser/Library/Caches/com.f5networks.EdgeClient
if [[ -d "$F5CACHE" ]] 
then
    echo "F5Network Cache exists. Removing at $(date +%H:%M:%S)" | tee -a $logfile
    /bin/rm -rf /Users/$consoleUser/Library/Caches/com.f5networks.EdgeClient
else
echo "F5Network Cache does not exist" | tee -a $logfile
fi

# Check if dockutil is installed

if [[ -f "/usr/local/bin/dockutil" ]]
then
echo "Dockutil is installed. Trying to remove F5 dock icon" | tee -a $logfile
/usr/local/bin/dockutil --remove /Applications/"BIG-IP Edge Client.app" --allhomes
fi

echo "This is what is left from F5 on the device" | tee -a $logfile
echo $dirlist | tee -a $logfile

elif $choice="Remove F5 And Install Pulse";
then

#############################
# Install Pulse Secure VPN ##
#############################

beginInstall "Pulse Secure VPN"

sleep 1 
echo "Install Pulse Secure"
installer -pkg /Users/Shared/NetflixShared/PulseSecure.pkg -target /

sleep 5
echo "Install Pulse Mac OS FTE config."
'/Applications/Pulse Secure.app/Contents/Plugins/JamUI/./jamCommand' -importfile /Users/Shared/NetflixShared/fte_compset.20201026.pulsepreconfig

else

###########
# CLEANUP #
###########
# Remove additional components
sleep 2
rm -r /Users/Shared/NetflixShared/

echo "Configuration completed at $(date +%H:%M:%S)" | tee -a $logfile
fi
exit 0
